// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: stache/v1/cache.proto

package stachev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Ttl           *int64                 `protobuf:"varint,3,opt,name=ttl" json:"ttl,omitempty"`
	ContentType   *string                `protobuf:"bytes,4,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_stache_v1_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stache_v1_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_stache_v1_cache_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetTtl() int64 {
	if x != nil && x.Ttl != nil {
		return *x.Ttl
	}
	return 0
}

func (x *SetRequest) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_stache_v1_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stache_v1_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_stache_v1_cache_proto_rawDescGZIP(), []int{1}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_stache_v1_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stache_v1_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_stache_v1_cache_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	ContentType   *string                `protobuf:"bytes,2,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	ExpiresAtMs   *int64                 `protobuf:"varint,3,opt,name=expires_at_ms,json=expiresAtMs" json:"expires_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_stache_v1_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stache_v1_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_stache_v1_cache_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *GetResponse) GetExpiresAtMs() int64 {
	if x != nil && x.ExpiresAtMs != nil {
		return *x.ExpiresAtMs
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_stache_v1_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stache_v1_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_stache_v1_cache_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       *bool                  `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_stache_v1_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stache_v1_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_stache_v1_cache_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return false
}

type EntryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Size          *uint32                `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	ContentType   *string                `protobuf:"bytes,3,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	ExpiresAtMs   *int64                 `protobuf:"varint,4,opt,name=expires_at_ms,json=expiresAtMs" json:"expires_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryInfo) Reset() {
	*x = EntryInfo{}
	mi := &file_stache_v1_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryInfo) ProtoMessage() {}

func (x *EntryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stache_v1_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryInfo.ProtoReflect.Descriptor instead.
func (*EntryInfo) Descriptor() ([]byte, []int) {
	return file_stache_v1_cache_proto_rawDescGZIP(), []int{6}
}

func (x *EntryInfo) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *EntryInfo) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *EntryInfo) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *EntryInfo) GetExpiresAtMs() int64 {
	if x != nil && x.ExpiresAtMs != nil {
		return *x.ExpiresAtMs
	}
	return 0
}

type ListEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_stache_v1_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stache_v1_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_stache_v1_cache_proto_rawDescGZIP(), []int{7}
}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*EntryInfo           `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_stache_v1_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stache_v1_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_stache_v1_cache_proto_rawDescGZIP(), []int{8}
}

func (x *ListEntriesResponse) GetEntries() []*EntryInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BatchGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_stache_v1_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stache_v1_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_stache_v1_cache_proto_rawDescGZIP(), []int{9}
}

func (x *BatchGetRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type BatchGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetResponseItem     `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
	mi := &file_stache_v1_cache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stache_v1_cache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return file_stache_v1_cache_proto_rawDescGZIP(), []int{10}
}

func (x *BatchGetResponse) GetItems() []*GetResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	ContentType   *string                `protobuf:"bytes,3,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	ExpiresAtMs   *int64                 `protobuf:"varint,4,opt,name=expires_at_ms,json=expiresAtMs" json:"expires_at_ms,omitempty"`
	Found         *bool                  `protobuf:"varint,5,opt,name=found" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponseItem) Reset() {
	*x = GetResponseItem{}
	mi := &file_stache_v1_cache_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseItem) ProtoMessage() {}

func (x *GetResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_stache_v1_cache_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseItem.ProtoReflect.Descriptor instead.
func (*GetResponseItem) Descriptor() ([]byte, []int) {
	return file_stache_v1_cache_proto_rawDescGZIP(), []int{11}
}

func (x *GetResponseItem) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *GetResponseItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponseItem) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *GetResponseItem) GetExpiresAtMs() int64 {
	if x != nil && x.ExpiresAtMs != nil {
		return *x.ExpiresAtMs
	}
	return 0
}

func (x *GetResponseItem) GetFound() bool {
	if x != nil && x.Found != nil {
		return *x.Found
	}
	return false
}

var File_stache_v1_cache_proto protoreflect.FileDescriptor

const file_stache_v1_cache_proto_rawDesc = "" +
	"\n" +
	"\x15stache/v1/cache.proto\x12\tstache.v1\"i\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"\r\n" +
	"\vSetResponse\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"j\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\"\n" +
	"\rexpires_at_ms\x18\x03 \x01(\x03R\vexpiresAtMs\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"x\n" +
	"\tEntryInfo\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\"\n" +
	"\rexpires_at_ms\x18\x04 \x01(\x03R\vexpiresAtMs\"\x14\n" +
	"\x12ListEntriesRequest\"E\n" +
	"\x13ListEntriesResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.stache.v1.EntryInfoR\aentries\"%\n" +
	"\x0fBatchGetRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"D\n" +
	"\x10BatchGetResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.stache.v1.GetResponseItemR\x05items\"\x96\x01\n" +
	"\x0fGetResponseItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\"\n" +
	"\rexpires_at_ms\x18\x04 \x01(\x03R\vexpiresAtMs\x12\x14\n" +
	"\x05found\x18\x05 \x01(\bR\x05found2\xcc\x02\n" +
	"\fCacheService\x124\n" +
	"\x03Set\x12\x15.stache.v1.SetRequest\x1a\x16.stache.v1.SetResponse\x124\n" +
	"\x03Get\x12\x15.stache.v1.GetRequest\x1a\x16.stache.v1.GetResponse\x12=\n" +
	"\x06Delete\x12\x18.stache.v1.DeleteRequest\x1a\x19.stache.v1.DeleteResponse\x12L\n" +
	"\vListEntries\x12\x1d.stache.v1.ListEntriesRequest\x1a\x1e.stache.v1.ListEntriesResponse\x12C\n" +
	"\bBatchGet\x12\x1a.stache.v1.BatchGetRequest\x1a\x1b.stache.v1.BatchGetResponseB4Z2github.com/byytelope/stache/api/stache/v1;stachev1b\beditionsp\xe8\a"

var (
	file_stache_v1_cache_proto_rawDescOnce sync.Once
	file_stache_v1_cache_proto_rawDescData []byte
)

func file_stache_v1_cache_proto_rawDescGZIP() []byte {
	file_stache_v1_cache_proto_rawDescOnce.Do(func() {
		file_stache_v1_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stache_v1_cache_proto_rawDesc), len(file_stache_v1_cache_proto_rawDesc)))
	})
	return file_stache_v1_cache_proto_rawDescData
}

var file_stache_v1_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_stache_v1_cache_proto_goTypes = []any{
	(*SetRequest)(nil),          // 0: stache.v1.SetRequest
	(*SetResponse)(nil),         // 1: stache.v1.SetResponse
	(*GetRequest)(nil),          // 2: stache.v1.GetRequest
	(*GetResponse)(nil),         // 3: stache.v1.GetResponse
	(*DeleteRequest)(nil),       // 4: stache.v1.DeleteRequest
	(*DeleteResponse)(nil),      // 5: stache.v1.DeleteResponse
	(*EntryInfo)(nil),           // 6: stache.v1.EntryInfo
	(*ListEntriesRequest)(nil),  // 7: stache.v1.ListEntriesRequest
	(*ListEntriesResponse)(nil), // 8: stache.v1.ListEntriesResponse
	(*BatchGetRequest)(nil),     // 9: stache.v1.BatchGetRequest
	(*BatchGetResponse)(nil),    // 10: stache.v1.BatchGetResponse
	(*GetResponseItem)(nil),     // 11: stache.v1.GetResponseItem
}
var file_stache_v1_cache_proto_depIdxs = []int32{
	6,  // 0: stache.v1.ListEntriesResponse.entries:type_name -> stache.v1.EntryInfo
	11, // 1: stache.v1.BatchGetResponse.items:type_name -> stache.v1.GetResponseItem
	0,  // 2: stache.v1.CacheService.Set:input_type -> stache.v1.SetRequest
	2,  // 3: stache.v1.CacheService.Get:input_type -> stache.v1.GetRequest
	4,  // 4: stache.v1.CacheService.Delete:input_type -> stache.v1.DeleteRequest
	7,  // 5: stache.v1.CacheService.ListEntries:input_type -> stache.v1.ListEntriesRequest
	9,  // 6: stache.v1.CacheService.BatchGet:input_type -> stache.v1.BatchGetRequest
	1,  // 7: stache.v1.CacheService.Set:output_type -> stache.v1.SetResponse
	3,  // 8: stache.v1.CacheService.Get:output_type -> stache.v1.GetResponse
	5,  // 9: stache.v1.CacheService.Delete:output_type -> stache.v1.DeleteResponse
	8,  // 10: stache.v1.CacheService.ListEntries:output_type -> stache.v1.ListEntriesResponse
	10, // 11: stache.v1.CacheService.BatchGet:output_type -> stache.v1.BatchGetResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_stache_v1_cache_proto_init() }
func file_stache_v1_cache_proto_init() {
	if File_stache_v1_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stache_v1_cache_proto_rawDesc), len(file_stache_v1_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stache_v1_cache_proto_goTypes,
		DependencyIndexes: file_stache_v1_cache_proto_depIdxs,
		MessageInfos:      file_stache_v1_cache_proto_msgTypes,
	}.Build()
	File_stache_v1_cache_proto = out.File
	file_stache_v1_cache_proto_goTypes = nil
	file_stache_v1_cache_proto_depIdxs = nil
}
